#!/usr/bin/env python
#ais decoder, main app

from argparse import ArgumentParser
from gnuradio import ais

import time
import sys
import socket

def main():
    # Create Options Parser
    parser = ArgumentParser (conflict_handler="resolve")
    ais.radio.ais_radio.add_radio_options(parser)
    args = parser.parse_args ()
    tb = ais.radio.ais_radio(args)
    tb.run()
    tb.close()

if __name__ == '__main__':
    main()


